### ISSUE TITLE
Invisible copy icon

### ISSUE THREAD

**Issue by jdpnielsen** [ByteCrumb/Umbraco.Community.DeliveryApiExtensions#25]
### Which version of the package are you using?

12

### Which Umbraco version are you using? For example: 12.2.0 - don't just write v12

12.3.7

### Bug summary

Icon for copying values seems to be missing or hidden:

![image](https://github.com/ByteCrumb/Umbraco.Community.DeliveryApiExtensions/assets/8746698/3737ad2c-5be4-40c7-9b93-276887825f4e)

### Steps to reproduce

1. Install package
2. Open api content app
3. Attempt to find the missing icon/button

This is the relevant packages of my installation:
  
```xml
<PackageReference Include="Umbraco.Cms" Version="12.3.7" />
<PackageReference Include="Umbraco.Cms.Core" Version="12.3.7" />
<PackageReference Include="Umbraco.Community.DeliveryApiExtensions" Version="12.0.0" />
```

**Comment by lauraneto** [comment]
Hi @jdpnielsen ,

Thank you for reporting this issue.
It seems to only affect v12, so I have made a `12.0.1` release which should have it fixed!
Let me know if it still happens, or if you find any other issues 🙂

**Comment by jdpnielsen** [comment]
Hi @lauraneto 

I have updated to v12.0.1, but the icons are still not showing up unfortunately. What info can i provide to help investigate?

**Comment by lauraneto** [comment]
Hi @jdpnielsen ,

Sorry for the late reply.
I cannot reproduce the issue anymore (on a clean install of Umbraco 12.3.7 using 12.0.1 of the package).
My first suspicion now would be browser cache, could you try it in an incognito browser window?
If the issue still persists, please let me know if you have any other packages installed.

**Comment by jdpnielsen** [comment]
No worries! I resolved it by upgrading to v13, so if you aren't able to reproduce on a clean install of v12, this can probably be closed 👍
