### ISSUE TITLE
Add support for Umbraco 14

### ISSUE THREAD

**Issue by lauraneto** [ByteCrumb/Umbraco.Community.DeliveryApiExtensions#33]
### Feature summary

With the release of Umbraco 14 today we want to make sure we add support for it.
Some work was already done, but there are some finishing touches needed. I will try to keep this up to date! 🙂

**Comment by lauraneto** [comment]
Unfortunately V14 contains some big changes in the way that the Delivery API swagger is configured/generated, especially when it comes to polymorphism, which will also require big changes from our end.
Due to that it is taking longer to update the package. 😔

**Comment by lauraneto** [comment]
Just released a `14.0.0-beta.1` version to nuget.
All the existing functionality should be there, but it still needs testing and some cleaning/refactoring.

**Comment by rickbutterfield** [comment]
Upgraded my site to v14 and the beta package... works a treat!

**Comment by JBoye** [comment]
The beta seems to work on V14, but not on V15 RC

**Comment by lauraneto** [comment]
Finally released **14.0.0** 🎉
Also released a V15 beta version **15.0.0-beta.1** (using the latest RC).

If you find any problems, please let us know!
