### ISSUE TITLE
Missing dark mode support in V15

### ISSUE THREAD

**Issue by JBoye** [ByteCrumb/Umbraco.Community.DeliveryApiExtensions#45]
### Which version of the package are you using?

version 15.0.0-beta.1

### Which Umbraco version are you using? For example: 12.2.0 - don't just write v12

15.0.0-rc3

### Bug summary

![Skærmbillede 2024-11-12 kl  09 58 26](https://github.com/user-attachments/assets/e313ebc8-bcdc-49c7-b1da-1f1ce97fac6b)

Great to see V15 supported already - I know this is very minor, but the json is almost unreadable when using the dark theme in Umbraco 15

### Steps to reproduce

Turn on dark mode

**Comment by lauraneto** [comment]
Hi @JBoye ,
This has been added in `15.0.0`.
Let us know if it's working as expected!

**Comment by JBoye** [comment]
Yes much better! 
![Skærmbillede 2024-11-14 kl  12 11 06](https://github.com/user-attachments/assets/2375854b-7a4d-4ab4-b21d-f73b37dc38c1)
