### ISSUE TITLE
Not working in V15 Release 

### ISSUE THREAD

**Issue by JBoye** [ByteCrumb/Umbraco.Community.DeliveryApiExtensions#47]
### Which version of the package are you using?

15.0.0-beta.1

### Which Umbraco version are you using? For example: 12.2.0 - don't just write v12

15.0.0

### Bug summary

The extension was working in V15 RC3 but not currently in the final V15.0.0 (released today): 

`Unhandled exception. System.MissingMethodException: Method not found: 'System.String Umbraco.Extensions.StringExtensions.TrimEndExact(System.String, System.String)'.`

[exception.txt](https://github.com/user-attachments/files/17747071/exception.txt)

### Steps to reproduce

Install Umbraco V15, DeliveryApiExtensions and start the project

**Comment by lauraneto** [comment]
Hi @JBoye ,

Just pushed a `15.0.0` to nuget.
Let us know if it's working as expected!
If you are curious about the error, you can read the comments here: https://github.com/umbraco/Umbraco-CMS/pull/16625 🙂

**Comment by JBoye** [comment]
That was quick! Thank you
